import { Page } from "@playwright/test";
import { MainPage } from "./mainPage";
import { AlertsPage } from "./Alerts/alertsPage";
import { BrowserWindowsPage } from "./Alerts/browserWindowsPage";
import { FramesPage } from "./Alerts/framesPage";
import { ModalDialogsPage } from "./Alerts/modalDialogsPage";
import { NestedFramesPage } from "./Alerts/nestedFramesPage";
import { BookStoreAPIPage } from "./Book/bookStoreAPIPage";
import { BookStorePage } from "./Book/bookStorePage";
import { LoginPage } from "./Book/loginPage";
import { ProfilePage } from "./Book/profilePage";
import { BrokenLinksPage } from "./Elements/brokenLinksPage";
import { ButtonsPage } from "./Elements/buttonsPage";
import { CheckBoxPage } from "./Elements/checkBoxPage";
import { DynamicPage } from "./Elements/dynamicPage";
import { LinksPage } from "./Elements/linksPage";
import { RadioButtonPage } from "./Elements/radioButtonPage";
import { TextBoxPage } from "./Elements/textBoxPage";
import { UploadPage } from "./Elements/uploadPage";
import { WebTablesPage } from "./Elements/webTablesPage";
import { PracticeFormPage } from "./Forms/practiceFormPage";
import { DragabblePage } from "./Interactions/dragabblePage";
import { DroppablePage } from "./Interactions/droppablePage";
import { ResizablePage } from "./Interactions/resizablePage";
import { SelectablePage } from "./Interactions/selectablePage";
import { SortablePage } from "./Interactions/sortablePage";
import { AccordianPage } from "./Widgets/accordianPage";
import { AutoCompletePage } from "./Widgets/autoCompletePage";
import { DatePickerPage } from "./Widgets/datePickerPage";
import { MenuPage } from "./Widgets/menuPage";
import { ProgressBarPage } from "./Widgets/progressBarPage";
import { SelectMenuPage } from "./Widgets/selectMenuPage";
import { SliderPage } from "./Widgets/sliderPage";
import { TabsPage } from "./Widgets/tabsPage";
import { ToolTipsPage } from "./Widgets/toolTipsPage";

export class PageManager {
  page: Page;
  main;
  alerts;
  browserWindows;
  frames;
  modalDialog;
  nestedFrames;
  bookStore;
  bookStoreAPI;
  login;
  profile;
  brokenLinks;
  buttons;
  checkBox;
  dynamic;
  links;
  radioButton;
  textBox;
  upload;
  webTables;
  practiceForm;
  draggable;
  droppable;
  resizable;
  selectable;
  sortable;
  accordian;
  autoComplete;
  datePicker;
  menu;
  progressBar;
  selectMenu;
  slider;
  tabs;
  toolTips;

  constructor(page) {
    this.page = page;
    this.main = new MainPage(page);
    this.alerts = new AlertsPage(page);
    this.browserWindows = new BrowserWindowsPage(page);
    this.frames = new FramesPage(page);
    this.modalDialog = new ModalDialogsPage(page);
    this.nestedFrames = new NestedFramesPage(page);
    this.bookStore = new BookStorePage(page);
    this.bookStoreAPI = new BookStoreAPIPage(page);
    this.login = new LoginPage(page);
    this.profile = new ProfilePage(page);
    this.brokenLinks = new BrokenLinksPage(page);
    this.buttons = new ButtonsPage(page);
    this.checkBox = new CheckBoxPage(page);
    this.dynamic = new DynamicPage(page);
    this.links = new LinksPage(page);
    this.radioButton = new RadioButtonPage(page);
    this.textBox = new TextBoxPage(page);
    this.upload = new UploadPage(page);
    this.webTables = new WebTablesPage(page);
    this.practiceForm = new PracticeFormPage(page);
    this.draggable = new DragabblePage(page);
    this.droppable = new DroppablePage(page);
    this.resizable = new ResizablePage(page);
    this.selectable = new SelectablePage(page);
    this.sortable = new SortablePage(page);
    this.accordian = new AccordianPage(page);
    this.autoComplete = new AutoCompletePage(page);
    this.datePicker = new DatePickerPage(page);
    this.menu = new MenuPage(page);
    this.progressBar = new ProgressBarPage(page);
    this.selectMenu = new SelectMenuPage(page);
    this.slider = new SliderPage(page);
    this.tabs = new TabsPage(page);
    this.toolTips = new ToolTipsPage(page);
  }
}
